---
- name: Install essential packages via apt
  hosts: all
  become: true

  tasks:
    - name: "Install essential package"
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        loop:
          - git
          - vim
          - curl
          - sudo
          - dpkg
          - wget
          - zsh
          - unattended-upgrades