---
- name: New host setup
  hosts: all
  become: true

  vars:
    csjain_password: $6$lz64qob6oH4Ongcz$jGz20QjmcJEZiOAJkb0JmVUiB5EkjLTAlXrlQZXi1KbUiGZdULbtxoQrYkOuhPa/uCz.KHNmSr4bwvKHN.M6Z.
    ansible_password: $6$pyGyOae1t4CtG2/j$ZxIXAiiEsfTJABK19NWUnvGd6u399PCoz5zpc9mI88vR7W8UsUq9F/8t1B4.qKQi24gQreigGemYYybcL77Wh.

  tasks:
  - name: "1. Create users, especailly ansible, for task #2"
    ansible.builtin.import_tasks: add-users.yaml

  - name: "2. Copy ansible SSH key so that we can login and run tasks"
    ansible.builtin.import_tasks: add-sshkey.yaml