---
- name: Update and upgrade apt packages
  hosts: all
  become: true

  tasks:
    - name: Update / Upgrade / Autoremove packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true