---
- name: Add Ansible public ssh key
  hosts: all
  become: true

  tasks:
    - name: Install public keys
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "/home/ansible/.ssh/id_ed25519.pub"